# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmastermodel',
            name='timecard',
        ),
    ]
