# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-05 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_invite', models.IntegerField(default=0)),
                ('is_response', models.IntegerField(default=0)),
                ('invited_date', models.DateTimeField(auto_now_add=True)),
                ('is_perm_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True)),
                ('is_using_freetool', models.BooleanField(default=False)),
                ('freetool', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active_costcode', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Created By+', to=settings.AUTH_USER_MODEL)),
                ('sub_admins', models.ManyToManyField(related_name='SubAdmin', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Updated By+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_field', models.SlugField(blank=True, max_length=10)),
                ('code', models.CharField(db_index=True, max_length=15)),
                ('is_budget_freeze', models.BooleanField(default=False, verbose_name='budget status, freeze or not')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Project status, active or not')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('base_value', models.BigIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is delete')),
                ('deleted_on', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.OrganizationModel')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMasterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimecardHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateTimeField()),
                ('work_time', models.FloatField()),
                ('brake_time', models.FloatField()),
                ('overtime', models.FloatField(default='4')),
                ('double_overtime', models.FloatField(default='5')),
                ('total_hours', models.DecimalField(decimal_places=2, default='08.00', max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimecardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=16, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=16, null=True)),
                ('clock_in_address', models.CharField(blank=True, max_length=256)),
                ('clock_out_address', models.CharField(blank=True, max_length=256)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to=b'')),
                ('is_clocked_out', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetrack.ProjectModel')),
            ],
        ),
        migrations.CreateModel(
            name='TimecardSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='07:00')),
                ('first_break_start', models.TimeField(default='09:30')),
                ('first_break_end', models.TimeField(default='09:40')),
                ('lunch_time', models.TimeField(default='12:00')),
                ('lunch_end', models.TimeField(default='12:30')),
                ('second_break_start', models.TimeField(default='00:00')),
                ('second_break_end', models.TimeField(default='00:00')),
                ('finish_time', models.TimeField(default='02:30')),
                ('regular_hours', models.TimeField(default='08:00')),
                ('grace_period', models.FloatField(default='5')),
                ('overtime', models.FloatField(default='5')),
                ('double_overtime', models.FloatField(default='5')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('typical_notes', models.CharField(default='By signing here, the user acknowledges that this time card is accurate. The user also acknowledges that their password or bar code entry may be used as their digital signature for entries made into the system', max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.OrganizationModel')),
            ],
        ),
        migrations.CreateModel(
            name='TimecardStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.StatusMasterModel')),
                ('timecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.TimecardModel')),
            ],
        ),
        migrations.AddField(
            model_name='timecardhistorymodel',
            name='timecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.TimecardModel'),
        ),
        migrations.AddField(
            model_name='statusmastermodel',
            name='timecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.TimecardModel'),
        ),
        migrations.AddField(
            model_name='invitedusermodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.ProjectModel'),
        ),
        migrations.AddField(
            model_name='invitedusermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitedusermodel',
            name='user_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetrack.OrganizationModel'),
        ),
    ]
